apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world-service
  template:
    metadata:
      labels:
        app: hello-world-service
    spec:
      containers:
        - name: hello-world-service-container
          image: ajres/hello-world-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: APP_NAME
              value: "HelloWorldService-${POD_NAME}"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service-node-port
spec:
  type: NodePort
  selector:
    app: hello-world-service
  ports:
    - protocol: TCP
      port: 80       # Port to expose
      targetPort: 8080  # Port on the pod
      #nodePort: 32575  # NodePort range is typically 30000-32767
